baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'roxo-hugo'

#site menu
[menu]
    #Navbar Menus
    [[menu.nav]]
        name = 'Home'
        url = ''
        weight = 1
    [[menu.nav]]
        name = 'Superannauation Calculator'
        url = 'superannuation-calculator'
        weight = 2
    [[menu.nav]]
        name = 'Budget'
        url = 'budget'
        weight = 3
    [[menu.nav]]
        name = 'Infomration'
        url = 'information'
        weight = 4