baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'SuperWoman'
theme = 'roxo-hugo'

#site menu
[menu]
    #Navbar Menus
    [[menu.nav]]
        name = 'Home'
        url = ''
        weight = 1
    [[menu.nav]]
        name = 'Superannuation Calculator'
        url = 'superannuation-calculator'
        weight = 2
    [[menu.nav]]
        name = 'Budgeting'
        url = 'budget'
        weight = 3
    [[menu.nav]]
        name = 'Resources'
        url = 'resources'
        weight = 4